Configuring with multiple documents
cu-mkp/editioncrafter pull request #69
Opened 2024-01-15 21:17 UTC by ajolipa

### In this PR
Adds the option to configure the `EditionCrafter` component to accept multiple documents, by setting the `variorum` prop to true and passing in an object with document IDs as keys as the `documentInfo` object. 

For example, a variorum configuration could look like
```
<EditionCrafter config={{
    documentName: 'FHL_007548733_TAOS_BAPTISMS_BATCH_2 and eng-415-145a',
    variorum: true,
    documentInfo: {
      FHL_007548733_TAOS_BAPTISMS_BATCH_2: {
        documentName: 'Taos Baptisms Batch 2',
        transcriptionTypes: {
          translation: 'Translation',
          transcription: 'Transcription',
        },
        iiifManifest: 'https://cu-mkp.github.io/editioncrafter/taos-baptisms-example/iiif/manifest.json',
      },
      eng_415_145a: {
        documentName: 'Eng 415-145a',
        transcriptionTypes: {
          'eng-415-145a': 'Transcription',
        },
        iiifManifest: 'https://cu-mkp.github.io/bic-editioncrafter-data/eng-415-145a/iiif/manifest.json',
      },
    },
  }}
  />
```

This results in the following behavior, including the ability to unlock the two panes from each other and view a folio from one document on one side and another document on the other side:
![image](https://github.com/cu-mkp/editioncrafter/assets/110847635/63e755e4-0a53-4165-8d46-012c0082924c)
![image](https://github.com/cu-mkp/editioncrafter/assets/110847635/a8c10808-7347-4cae-a3dd-16df2415852d)
![image](https://github.com/cu-mkp/editioncrafter/assets/110847635/eb25b1ac-f49a-4e4d-af97-617b78306cbe)

### Notes and future work
- There is not a lot of flexibility or intelligent error handling built into the component props at the moment; if you use the wrong key for something, or forget to set `variorum` to true, etc., the viewer will crash.
- More work needs to be done on allowing you to truly decouple the behavior of the two sides; currently even if you are in unlocked mode, going to a new folio on the left side will reset the righthand side to show the text of that folio. Possibly when using the viewer for comparing multiple documents that behavior is not desirable and it should be possible to just operate within each pane of the viewer independently more easily.
- Currently I completely punted on dealing with the glossary; if `variorum` is set to true, then an empty glossary is returned. Presumably each document could come with its own glossary link, so instead of loading the glossary when initializing the grid view, I suppose it should be loaded from the proper manifest once a specific folio is chosen? But implementing that will take another chunk of work.

2024-01-18 13:22 UTC, NickLaiacona commented
This is a great start, very exciting! Some UI feedback:

* It would be great if, when in variorum mode, it defaulted to unlocked mode and defaulted to displaying the grids for the first two documents in the list. 
* Could we add a tiny grid icon (like the one below the zoom tool but smaller) to the left of the document name drop down? Then, when you click on or jump to a page, the grid icon remains there as a way to quickly get back to the grid view.
* The document name drop down should be in line with the Jump To input field. It should not break into its own line. It should also match font properties with the text in the rest of the toolbar.

2024-01-19 18:12 UTC, ajolipa commented
Implemented the bullet points suggested above; @NickLaiacona go ahead and re-review whenever you have a chance!

2024-01-19 20:46 UTC, NickLaiacona commented
@ajolipa looks great! only one comment here - when you are not in variorum mode and looking at the grid view, you just see the grid icon but nothing beside it. Could we display the name of the document there, not as a drop down but just a label?

2024-01-20 02:27 UTC, ajolipa commented
@NickLaiacona Implemented the document name display for the non-variorum grid mode. Look it over when you get a chance!

2024-01-22 15:25 UTC, NickLaiacona commented
@ajolipa this looks good - one last nit on this PR - could you remove the "View All" option from the drop down? I think it will just confuse folks.

2024-01-23 13:56 UTC, NickLaiacona requested changes
Found a bug: when you select a facs from the grid on the right pane, the name of the document in the title bar becomes the name of the document on the left. If you switch to transcription view and starting paging next or prev, you start seeing pages from the document on the left.

2024-01-23 17:01 UTC, ajolipa commented
@NickLaiacona Just did a push that should address these most recent concerns; let me know how it looks.

2024-01-23 18:37 UTC, NickLaiacona approved these changes
Looks good to me! 👍

2024-01-23 18:38 UTC, merged